# Generated by Django 2.2 on 2019-10-08 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain_c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output', models.CharField(max_length=500, verbose_name=[('d13579.com',), ('osmtv.cn',), ('kingbaly.com',), ('animater.cn',), ('xdl5566.com',), ('xindeli015.com',), ('bzj55.com',), ('f13579.com',), ('a1628.net',), ('deli2828.com',), ('xindeli099.com',), ('xindeli789.com',), ('xindeli168.com',)])),
            ],
        ),
    ]
