# Generated by Django 2.2 on 2019-10-09 00:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0002_remove_domain_c_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain_c',
            name='my_output',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
