# Generated by Django 2.2 on 2019-10-09 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_domain_c_my_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain_c',
            name='my_output',
            field=models.CharField(max_length=500, verbose_name='testing'),
        ),
    ]
