# Generated by Django 2.2 on 2019-10-09 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_auto_20191009_0042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Domain_c',
        ),
    ]
